<?php
/**
 * Template Name: News
 * Template Post Type: post
 */

get_header();

$post_id      = get_the_ID();
$post_content = apply_filters( 'the_content', get_the_content() );


/**
 * Add PDF size, PDF icon and download icon
 * to ordinary PDF links inside the ACF Course field.
 *
 * Links already generated by [selected_document]
 * are left unchanged.
 */
function srfti_add_pdf_info_to_course_content( $content ) {

    if ( empty( $content ) ) {
        return '';
    }

    $content = preg_replace_callback(
        '/<a\b([^>]*\bhref=(["\'])([^"\']+\.pdf(?:\?[^"\']*)?)\2[^>]*)>(.*?)<\/a>/is',
        function ( $matches ) {

            $attributes = $matches[1];
            $file_url   = html_entity_decode( $matches[3] );
            $link_text  = $matches[4];


            /*
             * IMPORTANT:
             * Do not process links already created by
             * the [selected_document] shortcode.
             */
            if (
                strpos( $attributes, 'pdf-download-link' ) !== false ||
                strpos( $link_text, 'pdf-icon' ) !== false
            ) {
                return $matches[0];
            }


            /*
             * Try to find the WordPress Media attachment.
             */
            $attachment_id = attachment_url_to_postid(
                $file_url
            );


            /*
             * Older links may use HTTP while
             * the site currently uses HTTPS.
             */
            if ( ! $attachment_id ) {

                $https_url = set_url_scheme(
                    $file_url,
                    'https'
                );

                $attachment_id = attachment_url_to_postid(
                    $https_url
                );
            }


            $file_path = '';


            /*
             * Get attachment file path.
             */
            if ( $attachment_id ) {

                $file_path = get_attached_file(
                    $attachment_id
                );
            }


            /*
             * Fallback for uploaded files that
             * attachment_url_to_postid() cannot resolve.
             */
            if (
                ! $file_path ||
                ! file_exists( $file_path )
            ) {

                $upload_dir = wp_upload_dir();

                $file_url_path = wp_parse_url(
                    $file_url,
                    PHP_URL_PATH
                );

                $upload_url_path = wp_parse_url(
                    $upload_dir['baseurl'],
                    PHP_URL_PATH
                );


                if (
                    $file_url_path &&
                    $upload_url_path &&
                    strpos(
                        $file_url_path,
                        $upload_url_path
                    ) === 0
                ) {

                    $relative_path = substr(
                        $file_url_path,
                        strlen( $upload_url_path )
                    );

                    $file_path =
                        $upload_dir['basedir'] .
                        $relative_path;
                }
            }


            /*
             * Get file size.
             */
            $file_size = '';


            if (
                $file_path &&
                file_exists( $file_path )
            ) {

                $bytes = filesize(
                    $file_path
                );


                if ( false !== $bytes ) {

                    $file_size = size_format(
                        $bytes,
                        2
                    );
                }
            }


            /*
             * Add pdf-download-link class.
             */
            $attributes = trim(
                $attributes
            );


            if (
                preg_match(
                    '/\bclass=(["\'])(.*?)\1/i',
                    $attributes
                )
            ) {

                $attributes = preg_replace(
                    '/\bclass=(["\'])(.*?)\1/i',
                    'class=$1$2 pdf-download-link$1',
                    $attributes
                );

            } else {

                $attributes .=
                    ' class="pdf-download-link"';
            }


            /*
             * Open PDF in a new tab.
             */
            if (
                ! preg_match(
                    '/\btarget=/i',
                    $attributes
                )
            ) {

                $attributes .=
                    ' target="_blank"';
            }


            /*
             * Security for target="_blank".
             */
            if (
                ! preg_match(
                    '/\brel=/i',
                    $attributes
                )
            ) {

                $attributes .=
                    ' rel="noopener noreferrer"';
            }


            /*
             * Build final link.
             *
             * Note:
             * We show only the file size.
             * The visible word "PDF" is not added here.
             */
            return
                '<a ' . $attributes . '>' .

                    $link_text .

                    ' <span class="pdf-icon" aria-hidden="true"></span>' .

                    (
                        $file_size
                        ? ' <span class="file-size">(' .
                            esc_html( $file_size ) .
                          ')</span>'
                        : ''
                    ) .

                    ' <span class="download-icon" aria-hidden="true"></span>' .

                    ' <span class="sr-only">' .
                        esc_html__(
                            'Download PDF, opens in a new tab',
                            'srft-theme'
                        ) .
                    '</span>' .

                '</a>';
        },
        $content
    );


    return $content;
}
?>


<section
    id="skip-to-content"
    class="article-container"
>

    <article class="narticle">


        <div
            role="article"
            style="grid-column: 3; margin: 0;"
        >

            <a
                href="#"
                class="c-headline__topic t-heading--topic"
            >

                <span>
                    <?php
                    echo esc_html__(
                        'Admission',
                        'srft-theme'
                    );
                    ?>
                </span>

            </a>


            <h1 class="nheadline">

                <?php
                echo esc_html(
                    get_the_title(
                        $post_id
                    )
                );
                ?>

            </h1>


            <p
                style="
                    margin: 1rem 0 0;
                    font-weight: 600;
                "
            >

                <time>

                    <?php
                    echo esc_html(
                        get_field(
                            'Course-Publish-Date'
                        )
                    );
                    ?>

                </time>

            </p>

        </div>



        <div
            style="
                grid-column: 2/5;
            "
        >

            <div
                style="
                    text-align: left;
                "
            >

                <?php

                $course_image = get_field(
                    'Course-Image'
                );

                $course_image_alt = get_field(
                    'Course-Image-Alt'
                );

                ?>


                <?php if ( $course_image ) : ?>

                    <img
                        src="<?php echo esc_url( $course_image ); ?>"
                        class="img-responsive"
                        alt="<?php echo esc_attr( $course_image_alt ); ?>"
                    >

                <?php endif; ?>

            </div>

        </div>



        <div
            style="
                border-top: 3px solid #000;
                grid-column: 3/4;
                margin: 0;
                padding: 0;
                text-align: center;
            "
        >


            <div
                style="
                    display: flex;
                    align-items: flex-end;
                    justify-content: center;
                    line-height: 32px;
                "
            >
            </div>


            <div
                style="
                    grid-column: 3/4;
                    line-height: 28px;
                    text-align: left;
                "
            >

                <div
                    style="
                        padding: 1rem;
                        text-align: center;
                    "
                >

                    <?php

                    /*
                     * Get ACF Course field.
                     */
                    $course_content = get_field(
                        'Course'
                    );


                    if ( $course_content ) {

                        /*
                         * First execute shortcodes such as:
                         *
                         * [selected_document id="8654"]
                         */
                        $course_content = do_shortcode(
                            $course_content
                        );


                        /*
                         * Then process only ordinary PDF links.
                         *
                         * Links created by selected_document
                         * already have pdf-download-link and
                         * will therefore be skipped.
                         */
                        $course_content =
                            srfti_add_pdf_info_to_course_content(
                                $course_content
                            );


                        echo wp_kses_post(
                            $course_content
                        );
                    }

                    ?>

                </div>

            </div>

        </div>

    </article>

</section>


<?php get_footer(); ?>