
<?php
/**
 * Template Name: Announcement
 * Template Post Type: post
 */

get_header();

$post_id = get_the_ID();

/**
 * Add PDF details and icons to links within announcement content.
 *
 * Only ordinary PDF links are modified.
 * Links already processed or generated by the
 * selected_document shortcode are left unchanged.
 */
if ( ! function_exists( 'srfti_add_pdf_info_to_course_content' ) ) {

    function srfti_add_pdf_info_to_course_content( $content ) {

        if ( empty( $content ) || ! is_string( $content ) ) {
            return $content;
        }

        $content = preg_replace_callback(
            '/<a\b([^>]*\bhref=(["\'])([^"\']+\.pdf(?:[?#][^"\']*)?)\2[^>]*)>(.*?)<\/a>/is',
            function ( $matches ) {

                $attributes = $matches[1];
                $file_url   = html_entity_decode(
                    $matches[3],
                    ENT_QUOTES,
                    'UTF-8'
                );
                $link_text  = $matches[4];

                /*
                 * Avoid duplicate icons.
                 */
                if (
                    strpos( $attributes, 'pdf-download-link' ) !== false ||
                    strpos( $link_text, 'pdf-icon' ) !== false ||
                    strpos( $link_text, 'download-icon' ) !== false
                ) {
                    return $matches[0];
                }

                /*
                 * Try to identify the PDF attachment.
                 */
                $attachment_id = attachment_url_to_postid(
                    $file_url
                );

                /*
                 * Handle links containing HTTP instead of HTTPS.
                 */
                if ( ! $attachment_id ) {
                    $attachment_id = attachment_url_to_postid(
                        set_url_scheme( $file_url, 'https' )
                    );
                }

                $file_path = '';

                if ( $attachment_id ) {
                    $file_path = get_attached_file(
                        $attachment_id
                    );
                }

                /*
                 * Fallback: locate PDF in WordPress uploads.
                 */
                if (
                    ! $file_path ||
                    ! is_file( $file_path )
                ) {

                    $upload_dir = wp_upload_dir();

                    $file_url_path = wp_parse_url(
                        $file_url,
                        PHP_URL_PATH
                    );

                    $upload_url_path = wp_parse_url(
                        $upload_dir['baseurl'],
                        PHP_URL_PATH
                    );

                    if (
                        $file_url_path &&
                        $upload_url_path &&
                        strpos(
                            $file_url_path,
                            trailingslashit( $upload_url_path )
                        ) === 0
                    ) {

                        $relative_path = substr(
                            $file_url_path,
                            strlen( $upload_url_path )
                        );

                        $candidate_path = wp_normalize_path(
                            $upload_dir['basedir'] . $relative_path
                        );

                        $base_dir = realpath(
                            $upload_dir['basedir']
                        );

                        $resolved_path = realpath(
                            $candidate_path
                        );

                        /*
                         * Ensure the resolved file is within
                         * the WordPress uploads directory.
                         */
                        if (
                            $base_dir &&
                            $resolved_path &&
                            strpos(
                                wp_normalize_path( $resolved_path ),
                                trailingslashit(
                                    wp_normalize_path( $base_dir )
                                )
                            ) === 0
                        ) {
                            $file_path = $resolved_path;
                        }
                    }
                }

                /*
                 * Determine file size.
                 */
                $file_size = '';

                if (
                    $file_path &&
                    is_file( $file_path ) &&
                    is_readable( $file_path )
                ) {

                    $bytes = filesize( $file_path );

                    if ( false !== $bytes ) {
                        $file_size = size_format(
                            $bytes,
                            2
                        );
                    }
                }

                /*
                 * Add the link class without deleting
                 * any existing classes.
                 */
                if (
                    preg_match(
                        '/\bclass=(["\'])(.*?)\1/i',
                        $attributes
                    )
                ) {

                    $attributes = preg_replace(
                        '/\bclass=(["\'])(.*?)\1/i',
                        'class=$1$2 pdf-download-link$1',
                        $attributes,
                        1
                    );

                } else {
                    $attributes .= ' class="pdf-download-link"';
                }

                /*
                 * Make the PDF open in a new tab.
                 */
                if (
                    preg_match(
                        '/\btarget=(["\']).*?\1/i',
                        $attributes
                    )
                ) {

                    $attributes = preg_replace(
                        '/\btarget=(["\']).*?\1/i',
                        'target="_blank"',
                        $attributes,
                        1
                    );

                } else {
                    $attributes .= ' target="_blank"';
                }

                /*
                 * Ensure a safe rel attribute.
                 */
                if (
                    preg_match(
                        '/\brel=(["\'])(.*?)\1/i',
                        $attributes,
                        $rel_matches
                    )
                ) {

                    $rel_values = preg_split(
                        '/\s+/',
                        trim( $rel_matches[2] )
                    );

                    $rel_values[] = 'noopener';
                    $rel_values[] = 'noreferrer';

                    $new_rel = implode(
                        ' ',
                        array_unique(
                            array_filter( $rel_values )
                        )
                    );

                    $attributes = preg_replace(
                        '/\brel=(["\'])(.*?)\1/i',
                        'rel="' . esc_attr( $new_rel ) . '"',
                        $attributes,
                        1
                    );

                } else {
                    $attributes .= ' rel="noopener noreferrer"';
                }

                /*
                 * Build PDF link:
                 * Title + PDF icon + size + download icon.
                 *
                 * Both icons are decorative.
                 * Screen readers receive descriptive text.
                 */
                $output = '<a ' . trim( $attributes ) . '>';

                $output .= $link_text;

                $output .=
                    ' <span class="pdf-icon" aria-hidden="true"></span>';

                if ( $file_size ) {

                    $output .=
                        ' <span class="file-size">(' .
                        esc_html( $file_size ) .
                        ')</span>';
                }

                $output .=
                    ' <span class="download-icon" aria-hidden="true"></span>';

                $output .=
                    ' <span class="sr-only">' .
                    esc_html__(
                        'PDF document, opens in a new tab',
                        'srft-theme'
                    ) .
                    '</span>';

                $output .= '</a>';

                return $output;
            },
            $content
        );

        return $content;
    }
}

/*
 * Get announcement content from ACF.
 * Retain the existing field name.
 */
$announcement_text = get_field( 'Announement-Text', $post_id );

if ( ! is_string( $announcement_text ) ) {
    $announcement_text = '';
}

/*
 * Apply WordPress content formatting
 * and process PDF links.
 */
$announcement_text = apply_filters(
    'the_content',
    $announcement_text
);

$announcement_text = srfti_add_pdf_info_to_course_content(
    $announcement_text
);

/*
 * Get optional announcement image.
 */
$announcement_image = get_field(
    'Announcement-Image',
    $post_id
);

$announcement_image_url = '';

if ( is_array( $announcement_image ) ) {

    $announcement_image_url = isset(
        $announcement_image['url']
    ) ? $announcement_image['url'] : '';

} elseif ( is_numeric( $announcement_image ) ) {

    $announcement_image_url = wp_get_attachment_url(
        (int) $announcement_image
    );

} elseif ( is_string( $announcement_image ) ) {

    $announcement_image_url = $announcement_image;
}

?>

<section id="skip-to-content" class="article-container">

    <article class="narticle">

        <!-- Announcement heading -->
        <div
            style="grid-column: 3; margin: 0;"
        >

            <span class="c-headline__topic t-heading--topic">
                <?php
                echo esc_html__(
                    'Announcement',
                    'srft-theme'
                );
                ?>
            </span>

            <h1 class="nheadline">
                <?php echo esc_html( get_the_title( $post_id ) ); ?>
            </h1>

            <p
                style="
                    margin: 1rem 0 0;
                    font-weight: 600;
                "
            >
                <time datetime="<?php echo esc_attr( get_the_date( 'c', $post_id ) ); ?>">
                    <?php echo esc_html( get_the_date( 'F j, Y', $post_id ) ); ?>
                </time>
            </p>

        </div>

        <!-- Announcement image -->
        <?php if ( ! empty( $announcement_image_url ) ) : ?>

            <div style="grid-column: 2 / 5;">

                <div style="text-align: center;">

                    <img
                        src="<?php echo esc_url( $announcement_image_url ); ?>"
                        class="img-responsive"
                        alt="<?php echo esc_attr( get_the_title( $post_id ) ); ?>"
                        loading="lazy"
                    >

                </div>

            </div>

        <?php endif; ?>

        <!-- Announcement content -->
        <div
            style="
                border-top: 3px solid #000;
                grid-column: 3 / 4;
                margin: 0;
                padding: 0;
                text-align: left;
            "
        >

            <div
                style="
                    grid-column: 3 / 4;
                    line-height: 28px;
                    text-align: left;
                "
            >

                <div
                    class="announcement-content"
                    style="padding: 1rem;"
                >

                    <?php
                    echo wp_kses_post( $announcement_text );
                    ?>

                </div>

            </div>

        </div>

    </article>

</section>

<?php get_footer(); ?>
